GET http://api.example.com/injuries

###

GET http://api.example.com/users

###

POST http://api.example.com/users/register
Content-Type: application/json

{
    "name": "Dev",
    "email": "dev@dev",
    "password": "dev"
}

###

POST http://api.example.com/users/login
Content-Type: application/json

{
    "name": "Name",
    "password": "Password"
}

###

GET http://localhost:5000/

###

DELETE http://api.example.com/users